<a href="https://colab.research.google.com/github/hk77921/ML-Learning/blob/master/Assignment_1_DS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# **Assignment - 1 : Getting Started**

---

This assignment will get you familiarized with python libraries required for ***data science*** and ***machine learning***. You will have to complete the code snippets and run them. 

## **Note :**   Use only the methods and attributes of the ```numpy``` library. **Do not** hard-code them. Avoid loops as much as possible.

---
## Part - 1
 In this part, you will work with the library ```numpy```. 




Import ```numpy``` with an alias name ```np```. Initialize two arrays $a$, $b$ of size $3 \times 5$ with random values and print them. 

In [0]:
import numpy as np
a = np.random.randn(3,5) # other ways of generating random matrices can be used
b = np.random.randn(3,5)
print(a)
print(b)

[[ 0.61195871  0.38217603 -0.68236175 -0.15892509  1.96583747]
 [-0.61209462 -0.97576868 -1.41185052 -0.43600697 -0.62069723]
 [-1.19921033  0.79724142  0.00913807  0.95889511  0.96877431]]
[[ 0.76449883  1.22049555  0.7276404  -0.34079606 -0.91695982]
 [ 1.16265281 -0.85978275 -0.16199222  0.5475104   1.82794479]
 [ 0.60647257 -0.10568797 -0.20948251  1.14896012 -0.20090212]]


Initialize and print two arrays $c$ and $d$ having the following properties:
*   $c$ is a row vector with all non-negative integer values less than 100
* $d$ is a square matrix of size 3 having all entries as 0.0

In [0]:
c = np.arange(100)
d =  np.zeros((3,3))
print(c)
print(d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


We have $e$ as following : ```e = [[1,2,3],[4,5,6],[7,8,9]]```. Change $e$ as a numpy array and print it.

In [0]:
e = [[1,2,3],[4,5,6],[7,8,9]]
e = np.array(e)
print(e)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


$f$ and $g$ are two square matrices of size 5 such that all the entries of $f$ are 1 and $g$ is an identity matrix. Initialize them and print them

In [0]:
f = np.ones((5,5))
g = np.eye(5)
print(f)
print(g)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Reshape $c$ into a $10 \times 10$ matrix and name it $h$. Now flatten $h$, call it $c^\prime$ and print **YES** when the shapes of $c$ and $c^\prime$ are same. Otherwise print **NO**.

In [0]:
h = c.reshape((10,10))
c1 = h.flatten()
if c.shape == c1.shape:
    print('YES')
else:
    print('NO')

YES


Let $A$ denote a randomly initialized three dimensional matrix of shape (2,10,5). Transpose $A$, call it $A^\prime$, such that its shape is (5,2,10) and print it.

In [0]:
A = np.random.rand(2,10,5)
A1 = A.transpose((2,0,1))
print(A1)

[[[0.41498249 0.86686513 0.171562   0.82520892 0.69569285 0.93362086
   0.30179554 0.72475212 0.15085875 0.65612936]
  [0.69966346 0.39819878 0.55712325 0.82272745 0.48868539 0.75457217
   0.11725948 0.01612617 0.32950618 0.73030181]]

 [[0.3260295  0.44758707 0.28628745 0.53020913 0.41902315 0.47110014
   0.96811658 0.71680466 0.9432538  0.10244485]
  [0.74080412 0.11484139 0.80520487 0.11238544 0.59938459 0.00369666
   0.22153989 0.58221796 0.47581252 0.09480063]]

 [[0.48613106 0.89822483 0.72020072 0.10060898 0.08471619 0.49283806
   0.17031651 0.81546668 0.78815408 0.34814919]
  [0.57199322 0.88217415 0.57503725 0.53171562 0.19290661 0.9246967
   0.39882931 0.88687789 0.37678915 0.30872776]]

 [[0.31571857 0.38491208 0.31595014 0.57352585 0.56495883 0.13845472
   0.59918801 0.17341382 0.32004504 0.25337371]
  [0.21527382 0.19509818 0.49448193 0.96464614 0.96162034 0.89312486
   0.35038275 0.70483104 0.13661291 0.3844174 ]]

 [[0.14629431 0.31180878 0.933037   0.0299277  0.5112558 

You have a matrix $X$ of size (10,5) filled with random values. Print the following :
* Minimum value and index where it occured, for each column
* Maximum value and the index where it occured, for each column
* Minimum value and index where it occured, for each row
* Maximum value and index where it occured, for each row
* Minimum value and index where it occured, for the entire matrix
* Maximum value and index where it occured, for the entire matrix

In [0]:
np.random.seed(0)
X = np.random.rand(10,5)
print(np.min(X,axis=0),np.argmin(X,axis=0))
print(np.max(X,axis=0),np.argmax(X,axis=0))
print(np.min(X,axis=1),np.argmin(X,axis=1))
print(np.max(X,axis=1),np.argmax(X,axis=1))
print(np.min(X),np.argmin(X))
print(np.max(X),np.argmax(X))

[0.0871293  0.0202184  0.1289263  0.06022547 0.0187898 ] [3 3 9 8 6]
[0.97861834 0.79915856 0.94466892 0.96366276 0.87001215] [4 4 5 1 3]
[0.4236548  0.38344152 0.07103606 0.0202184  0.11827443 0.14335329
 0.0187898  0.61209572 0.06022547 0.1289263 ] [4 4 4 1 4 1 4 1 3 2]
[0.71518937 0.96366276 0.92559664 0.87001215 0.97861834 0.94466892
 0.77423369 0.94374808 0.6976312  0.67063787] [1 3 3 4 0 2 1 3 2 0]
0.018789800436355142 34
0.978618342232764 20


Find and print the following for the matrix X: 
* Mean of each row and column
* Standard deviation of each row and column
* Mean of the entire matrix
* Standard deviation of entire matrix

In [0]:
print(np.mean(X,axis=1),np.mean(X,axis=0))
print(np.std(X,axis=1),np.std(X,axis=0))
print(np.mean(X))
print(np.std(X))

[0.56706085 0.66447172 0.57705944 0.51762729 0.62761197 0.5328907
 0.41643268 0.69444672 0.44423265 0.33781717] [0.56044382 0.46781457 0.62009909 0.64025127 0.40121685]
[0.09445299 0.23322986 0.29189733 0.38052993 0.30431633 0.26338419
 0.25841437 0.12727959 0.23169975 0.18537332] [0.24687647 0.25752158 0.22948615 0.28054144 0.26584905]
0.5379651182755409
0.27226582292177587


Let $Y$ denote a square matrix of size 10 with random values. Print the following:
* Determinant
* Rank of the matrix
* Diagonal Elements
* Trace
* Eigen values
* Matrices obtained after Singular Value Decomposition
* Inverse if exists, otherwise Pseudo-Inverse
* Multiplication $Y$ with $X$
* Element-wise multiplication of $Y$ and its inverse(or pseudo-inverse)

In [0]:
np.random.seed(3)
Y = np.random.rand(10,10)
print(np.linalg.det(Y))
print(np.linalg.matrix_rank(Y))
print(np.diag(Y))
print(np.trace(Y))
print(np.linalg.eigvals(Y))
print(np.linalg.svd(Y))
print(np.linalg.pinv(Y))
print(np.matmul(Y,X))
print(np.dot(Y,np.linalg.pinv(Y)))

-0.012807808169095483
10
[0.5507979  0.45683322 0.44045372 0.84575087 0.4576864  0.36217621
 0.06152893 0.19897603 0.92672568 0.19638058]
4.497309545724899
[ 4.797525  +0.j          0.72411408+0.52238181j  0.72411408-0.52238181j
 -0.48250062+0.55413671j -0.48250062-0.55413671j -0.6909002 +0.j
 -0.25905659+0.32357377j -0.25905659-0.32357377j  0.2127855 +0.08352477j
  0.2127855 -0.08352477j]
(array([[-0.31776408, -0.02455508, -0.60644878, -0.17883359, -0.12672161,
         0.14873878, -0.17823942, -0.52859453, -0.02295855, -0.38570883],
       [-0.26118514, -0.10864541, -0.24911354,  0.26547359,  0.52168399,
        -0.25773901, -0.46995326,  0.21752636, -0.39285046,  0.16234491],
       [-0.31347907, -0.34483471, -0.25292297,  0.1214296 ,  0.1486964 ,
         0.33436315,  0.54080229,  0.48017168,  0.05660692, -0.20966421],
       [-0.35815379,  0.59490017,  0.30255161,  0.15850614, -0.11046295,
         0.3051409 ,  0.07395537,  0.03044889, -0.50561658, -0.18384856],
       [-0.2838584

## End of Part - 1
 --- --- ---

## Part - 2
---
In this part, you will be working with the library ```pandas```. Import this library with an alias name ```pd```.

In [0]:
# Initial imports
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Download dataset from: http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.csv
Read the data and display the first 5 rows

In [0]:
#Download dataset from: http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.csv

file_url = "http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.csv"
data = pd.read_csv(file_url)
data.head()

pclass  survived  ...   body                        home.dest
0       1         1  ...    NaN                     St Louis, MO
1       1         1  ...    NaN  Montreal, PQ / Chesterville, ON
2       1         0  ...    NaN  Montreal, PQ / Chesterville, ON
3       1         0  ...  135.0  Montreal, PQ / Chesterville, ON
4       1         0  ...    NaN  Montreal, PQ / Chesterville, ON

[5 rows x 14 columns]

### Preprocessing of the Dataset



---


**1. Convert the categorical values of columns 'sex', 'embarked', 'pclass' into dummy values and add them into titanic_data_new DataFrame**




---



In [0]:
sex = pd.get_dummies(data.sex)
embarked = pd.get_dummies(data.embarked)
pclass = pd.get_dummies(data.pclass)
titanic_data_new = pd.concat([sex,embarked,pclass],axis=1)
titanic_data_new

female  male  C  Q  S  1  2  3
0          1     0  0  0  1  1  0  0
1          0     1  0  0  1  1  0  0
2          1     0  0  0  1  1  0  0
3          0     1  0  0  1  1  0  0
4          1     0  0  0  1  1  0  0
...      ...   ... .. .. .. .. .. ..
1304       1     0  1  0  0  0  0  1
1305       1     0  1  0  0  0  0  1
1306       0     1  1  0  0  0  0  1
1307       0     1  1  0  0  0  0  1
1308       0     1  0  0  1  0  0  1

[1309 rows x 8 columns]



---


**2. Fill the missing data in Age and Fare columns with the mean value of the respected column then add these columns to titanic_data_new**


---



In [0]:
age = data['age'].fillna(data.age.mean())
fare = data['fare'].fillna(data.fare.mean())
titanic_data_new = pd.concat([titanic_data_new,age,fare],axis=1)
titanic_data_new.head()

female  male  C  Q  S  1  2  3    age      fare
0       1     0  0  0  1  1  0  0  29.00  211.3375
1       0     1  0  0  1  1  0  0   0.92  151.5500
2       1     0  0  0  1  1  0  0   2.00  151.5500
3       0     1  0  0  1  1  0  0  30.00  151.5500
4       1     0  0  0  1  1  0  0  25.00  151.5500

###Normalization


---



1. Normalize the columns which have numerical data



---





---
2. Drop the original age, fare columns
3. Append the normalized columns to the titanic_data_new DataFrame.



---



###Plotting
1. plot the age against the ID(continuous)
2. plot the fare against the ID(scatter)

## End of Part - 2
---

## Part - 3
---

In this part, you will work with the library ```matplotlib```. Import the ```pyplot``` from ```matplotlib``` with an alias name ```plt```.

Plot the sine function with domain in $[-3\pi,3\pi]$. Label the axes appropriately. Add title $\sin(x)$. Use latex formatting while adding the title. Set the plot size to (10,10)

Plot $\sin(x)$ and its spectrum, $\cos(x)$ and its spectrum in a single plot, in the domain $[-2\pi,2\pi]$. Label the plot appropriately.

## End of Part - 3
---

Create a Github repository with the name ***SHALA2020*** and save this assignment there.